SignIn UI completed
Pavithrank02/Home pull request #10
Opened 2022-12-24 13:16 UTC by Pavithrank02

2022-12-29 14:08 UTC, gowrishankkar requested changes

2022-12-29 14:08 UTC, gowrishankkar commented on src/SignIn.jsx
> +    <div className="signin">
Use Grid

2022-12-29 14:08 UTC, gowrishankkar commented on src/Styles.css
> +form{
Dont use form tag

2022-12-29 14:08 UTC, gowrishankkar commented on src/Styles.css
> +.home > a{
use typography

2022-12-30 10:18 UTC, Pavithrank02 commented on src/SignIn.jsx
> +    <div className="signin">
completed

2022-12-30 10:18 UTC, Pavithrank02 commented on src/Styles.css
> +form{
completed

2022-12-30 10:19 UTC, Pavithrank02 commented on src/Styles.css
> +.home > a{
completed

2022-12-30 10:47 UTC, gowrishankkar approved these changes

2022-12-30 10:47 UTC, gowrishankkar commented on src/Styles.css
> +.home > a{
If you've used typography, then remove this css

2022-12-30 10:48 UTC, merged